<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
// Retrieve order
$orderId     = $block->getLastOrderId();
$payemntData = $block->getPaymentData();
$quoteData   = $block->getQuote();
$successUrl  = $block->getSuccessUrl();
$failUrl     = $block->getFailUrl();
?>
<form name="onetwothreecoinpayform" method="post" action="https://123coinpay.com/payment/button_pay">


    <input type="hidden" name="merchant" value="<?php echo $payemntData['merchant_id']; ?>">

    <input type="hidden" name="request_id" value="<?php echo $orderId; ?>">
    <input type="hidden" name="redirect_url" value="<?php echo $successUrl; ?>">
    <input type="hidden" name="callback_url" value="<?php echo htmlspecialchars($block->getIpnUrl(), ENT_QUOTES, 'utf-8'); ?>">


    <input type="hidden" name="item_name" value="<?php echo $payemntData['item_name']; ?> Order #<?php echo $orderId; ?>">
    <!-- <input type="hidden" name="invoice" value="<?php echo $orderId; ?>">
    <input type="hidden" name="custom" value="<?php echo $payemntData['store_id']; ?>"> -->
    <input type="hidden" name="quantity" value="1">

    <input type="hidden" name="currency_code" value="<?php echo htmlspecialchars(
        $payemntData['currency_code'],
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <input type="hidden" name="shipping_amount" value="<?php echo $block->getShippingAmount(); ?>">
    <input type="hidden" name="tax_amount" value="<?php echo $quoteData->getShippingAddress()->getTaxAmount(); ?>">
    <input type="hidden" name="amount" value="<?php echo $quoteData->getSubtotalWithDiscount(); ?>">

    <input type="hidden" name="email" value="<?php echo htmlspecialchars(
        $quoteData->getCustomerEmail(),
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <input type="hidden" name="first_name" value="<?php echo htmlspecialchars(
        $quoteData->getBillingAddress()->getFirstname(),
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <input type="hidden" name="last_name" value="<?php echo htmlspecialchars(
        $quoteData->getBillingAddress()->getLastname(),
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <noscript><input type="submit" value="Click here to complete checkout at 123coinpay.com"></noscript>
</form>
<script type="text/javascript">
    document.onetwothreecoinpayform.submit();
</script>
